-- PARYX PLATFORM
-- Migration 004: Paryx Console foundation
--
-- PURPOSE
-- 1. Create a platform-level permission layer that is separate from club roles.
-- 2. Provide secure RPCs for the internal Paryx Console.
-- 3. Allow platform owners/admins to create, inspect, suspend and reactivate
--    tenant clubs without exposing elevated database credentials to browsers.
-- 4. Create a platform audit trail.
--
-- IMPORTANT
-- After this migration succeeds, run the separate bootstrap file:
-- supabase/setup/004_bootstrap_platform_owner.sql
-- to make your existing Supabase Auth account the first platform_owner.

begin;

-- =========================================================
-- PLATFORM USERS
-- =========================================================

create table if not exists public.platform_users (
    user_id uuid primary key
        references auth.users(id)
        on delete cascade,

    role text not null,
    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint platform_users_role_valid
        check (
            role in (
                'platform_owner',
                'platform_admin',
                'platform_support'
            )
        )
);

alter table public.platform_users
    enable row level security;

-- Deliberately no direct browser policies.
-- All Console reads/writes go through SECURITY DEFINER RPCs after a role check.


-- =========================================================
-- PLATFORM AUDIT LOG
-- =========================================================

create table if not exists public.platform_audit_log (
    id bigint generated by default as identity primary key,

    actor_user_id uuid
        references auth.users(id)
        on delete set null,

    actor_role text,

    action text not null,

    club_id uuid
        references public.clubs(id)
        on delete set null,

    target_user_id uuid
        references auth.users(id)
        on delete set null,

    details jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),

    constraint platform_audit_action_not_blank
        check (length(trim(action)) > 0)
);

create index if not exists platform_audit_log_created_at_idx
    on public.platform_audit_log(created_at desc);

create index if not exists platform_audit_log_club_id_idx
    on public.platform_audit_log(club_id);

create index if not exists platform_audit_log_actor_user_id_idx
    on public.platform_audit_log(actor_user_id);

alter table public.platform_audit_log
    enable row level security;

-- Deliberately no direct browser policies.


-- =========================================================
-- PLATFORM ACCESS HELPER
-- =========================================================

create or replace function public.is_platform_user(
    p_roles text[] default null
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.platform_users as pu
        where pu.user_id = auth.uid()
          and pu.is_active = true
          and (
              p_roles is null
              or pu.role = any(p_roles)
          )
    );
$$;

revoke all
on function public.is_platform_user(text[])
from public, anon;

grant execute
on function public.is_platform_user(text[])
to authenticated;


-- =========================================================
-- CURRENT PLATFORM ACCESS
-- =========================================================

create or replace function public.get_my_platform_access()
returns table (
    user_id uuid,
    email text,
    role text,
    is_active boolean
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        au.id,
        au.email::text,
        pu.role,
        pu.is_active
    from public.platform_users as pu
    join auth.users as au
        on au.id = pu.user_id
    where pu.user_id = auth.uid()
      and pu.is_active = true
    limit 1;
$$;

revoke all
on function public.get_my_platform_access()
from public, anon;

grant execute
on function public.get_my_platform_access()
to authenticated;


-- =========================================================
-- CONSOLE OVERVIEW
-- =========================================================

create or replace function public.get_platform_console_overview()
returns table (
    total_clubs bigint,
    active_clubs bigint,
    inactive_clubs bigint,
    total_auth_users bigint,
    active_memberships bigint,
    total_courses bigint,
    platform_users bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null
       or not public.is_platform_user(null) then
        raise exception 'Paryx Console access required.';
    end if;

    return query
    select
        (select count(*) from public.clubs)::bigint,
        (select count(*) from public.clubs where is_active = true)::bigint,
        (select count(*) from public.clubs where is_active = false)::bigint,
        (select count(*) from auth.users)::bigint,
        (
            select count(*)
            from public.club_memberships
            where status = 'active'
        )::bigint,
        (select count(*) from public.courses)::bigint,
        (
            select count(*)
            from public.platform_users
            where is_active = true
        )::bigint;
end;
$$;

revoke all
on function public.get_platform_console_overview()
from public, anon;

grant execute
on function public.get_platform_console_overview()
to authenticated;


-- =========================================================
-- CLUB DIRECTORY
-- =========================================================

create or replace function public.platform_list_clubs(
    p_search text default null,
    p_limit integer default 100,
    p_offset integer default 0
)
returns table (
    club_id uuid,
    club_name text,
    club_slug text,
    club_timezone text,
    is_active boolean,
    created_at timestamptz,
    member_count bigint,
    staff_count bigint,
    course_count bigint,
    upcoming_event_count bigint,
    total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_search text;
    v_limit integer;
    v_offset integer;
begin
    if auth.uid() is null
       or not public.is_platform_user(null) then
        raise exception 'Paryx Console access required.';
    end if;

    v_search := nullif(
        lower(trim(coalesce(p_search, ''))),
        ''
    );

    v_limit := greatest(
        1,
        least(coalesce(p_limit, 100), 250)
    );

    v_offset := greatest(
        0,
        coalesce(p_offset, 0)
    );

    return query
    with filtered as (
        select
            c.id,
            c.name,
            c.slug,
            c.timezone,
            c.is_active,
            c.created_at
        from public.clubs as c
        where (
            v_search is null
            or lower(c.name) like '%' || v_search || '%'
            or lower(c.slug) like '%' || v_search || '%'
        )
    ),
    counted as (
        select count(*)::bigint as total_count
        from filtered
    )
    select
        f.id,
        f.name,
        f.slug,
        f.timezone,
        f.is_active,
        f.created_at,
        (
            select count(*)
            from public.club_memberships as cm
            where cm.club_id = f.id
              and cm.status = 'active'
        )::bigint as member_count,
        (
            select count(*)
            from public.club_memberships as cm
            where cm.club_id = f.id
              and cm.status = 'active'
              and cm.role in (
                  'starter',
                  'reception',
                  'professional',
                  'greenkeeper',
                  'manager',
                  'club_admin'
              )
        )::bigint as staff_count,
        (
            select count(*)
            from public.courses as course
            where course.club_id = f.id
        )::bigint as course_count,
        (
            select count(*)
            from public.club_events as ce
            where ce.club_id = f.id
              and ce.event_date >= current_date
              and ce.status <> 'cancelled'
        )::bigint as upcoming_event_count,
        counted.total_count
    from filtered as f
    cross join counted
    order by
        f.is_active desc,
        lower(f.name)
    limit v_limit
    offset v_offset;
end;
$$;

revoke all
on function public.platform_list_clubs(text, integer, integer)
from public, anon;

grant execute
on function public.platform_list_clubs(text, integer, integer)
to authenticated;


-- =========================================================
-- CREATE CLUB
-- =========================================================

create or replace function public.platform_create_club(
    p_name text,
    p_slug text,
    p_timezone text default 'Europe/London'
)
returns table (
    club_id uuid,
    club_name text,
    club_slug text,
    club_timezone text,
    is_active boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_name text;
    v_slug text;
    v_timezone text;
    v_club_id uuid;
    v_actor_role text;
begin
    if auth.uid() is null
       or not public.is_platform_user(
            array['platform_owner', 'platform_admin']
       ) then
        raise exception 'Paryx platform admin access required.';
    end if;

    select pu.role
    into v_actor_role
    from public.platform_users as pu
    where pu.user_id = auth.uid()
      and pu.is_active = true
    limit 1;

    v_name := nullif(trim(p_name), '');
    v_slug := lower(nullif(trim(p_slug), ''));
    v_timezone := coalesce(
        nullif(trim(p_timezone), ''),
        'Europe/London'
    );

    if v_name is null then
        raise exception 'Club name is required.';
    end if;

    if v_slug is null
       or v_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
        raise exception
            'Slug must use lowercase letters, numbers and single hyphens.';
    end if;

    if not exists (
        select 1
        from pg_catalog.pg_timezone_names as tz
        where tz.name = v_timezone
    ) then
        raise exception 'Invalid timezone.';
    end if;

    insert into public.clubs (
        name,
        slug,
        timezone,
        is_active
    )
    values (
        v_name,
        v_slug,
        v_timezone,
        true
    )
    returning id into v_club_id;

    insert into public.platform_audit_log (
        actor_user_id,
        actor_role,
        action,
        club_id,
        details
    )
    values (
        auth.uid(),
        v_actor_role,
        'club_created',
        v_club_id,
        jsonb_build_object(
            'name', v_name,
            'slug', v_slug,
            'timezone', v_timezone
        )
    );

    return query
    select
        c.id,
        c.name,
        c.slug,
        c.timezone,
        c.is_active
    from public.clubs as c
    where c.id = v_club_id;
end;
$$;

revoke all
on function public.platform_create_club(text, text, text)
from public, anon;

grant execute
on function public.platform_create_club(text, text, text)
to authenticated;


-- =========================================================
-- ACTIVATE / SUSPEND CLUB
-- =========================================================

create or replace function public.platform_set_club_active(
    p_club_id uuid,
    p_is_active boolean,
    p_reason text default null
)
returns table (
    club_id uuid,
    club_name text,
    is_active boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor_role text;
    v_club_name text;
    v_old_active boolean;
begin
    if auth.uid() is null
       or not public.is_platform_user(
            array['platform_owner', 'platform_admin']
       ) then
        raise exception 'Paryx platform admin access required.';
    end if;

    select pu.role
    into v_actor_role
    from public.platform_users as pu
    where pu.user_id = auth.uid()
      and pu.is_active = true
    limit 1;

    select c.name, c.is_active
    into v_club_name, v_old_active
    from public.clubs as c
    where c.id = p_club_id
    limit 1;

    if v_club_name is null then
        raise exception 'Club not found.';
    end if;

    update public.clubs as c
    set
        is_active = coalesce(p_is_active, false),
        updated_at = now()
    where c.id = p_club_id;

    insert into public.platform_audit_log (
        actor_user_id,
        actor_role,
        action,
        club_id,
        details
    )
    values (
        auth.uid(),
        v_actor_role,
        case
            when coalesce(p_is_active, false)
                then 'club_reactivated'
            else 'club_suspended'
        end,
        p_club_id,
        jsonb_build_object(
            'club_name', v_club_name,
            'previous_active', v_old_active,
            'new_active', coalesce(p_is_active, false),
            'reason', nullif(trim(coalesce(p_reason, '')), '')
        )
    );

    return query
    select
        c.id,
        c.name,
        c.is_active
    from public.clubs as c
    where c.id = p_club_id;
end;
$$;

revoke all
on function public.platform_set_club_active(uuid, boolean, text)
from public, anon;

grant execute
on function public.platform_set_club_active(uuid, boolean, text)
to authenticated;


-- =========================================================
-- PLATFORM USER DIRECTORY
-- =========================================================

create or replace function public.platform_list_platform_users()
returns table (
    user_id uuid,
    email text,
    display_name text,
    role text,
    is_active boolean,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null
       or not public.is_platform_user(null) then
        raise exception 'Paryx Console access required.';
    end if;

    return query
    select
        pu.user_id,
        au.email::text,
        coalesce(
            nullif(trim(p.display_name), ''),
            nullif(trim(concat_ws(' ', p.first_name, p.last_name)), ''),
            au.email::text
        ) as display_name,
        pu.role,
        pu.is_active,
        pu.created_at,
        pu.updated_at
    from public.platform_users as pu
    join auth.users as au
        on au.id = pu.user_id
    left join public.profiles as p
        on p.id = pu.user_id
    order by
        case pu.role
            when 'platform_owner' then 1
            when 'platform_admin' then 2
            else 3
        end,
        lower(coalesce(au.email::text, ''));
end;
$$;

revoke all
on function public.platform_list_platform_users()
from public, anon;

grant execute
on function public.platform_list_platform_users()
to authenticated;


-- =========================================================
-- OWNER-ONLY PLATFORM USER MANAGEMENT
-- =========================================================

create or replace function public.platform_set_user_access(
    p_email text,
    p_role text,
    p_is_active boolean default true
)
returns table (
    user_id uuid,
    email text,
    role text,
    is_active boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_email text;
    v_role text;
    v_target_user_id uuid;
    v_old_role text;
    v_old_active boolean;
    v_active_owner_count bigint;
begin
    if auth.uid() is null
       or not public.is_platform_user(
            array['platform_owner']
       ) then
        raise exception 'Paryx platform owner access required.';
    end if;

    v_email := lower(nullif(trim(p_email), ''));
    v_role := lower(nullif(trim(p_role), ''));

    if v_email is null then
        raise exception 'Email address is required.';
    end if;

    if v_role not in (
        'platform_owner',
        'platform_admin',
        'platform_support'
    ) then
        raise exception 'Invalid platform role.';
    end if;

    select au.id
    into v_target_user_id
    from auth.users as au
    where lower(au.email) = v_email
    limit 1;

    if v_target_user_id is null then
        raise exception
            'That email address does not belong to an existing Paryx account.';
    end if;

    select pu.role, pu.is_active
    into v_old_role, v_old_active
    from public.platform_users as pu
    where pu.user_id = v_target_user_id;

    if v_old_role = 'platform_owner'
       and coalesce(v_old_active, false) = true
       and (
            v_role <> 'platform_owner'
            or coalesce(p_is_active, false) = false
       ) then

        select count(*)
        into v_active_owner_count
        from public.platform_users as pu
        where pu.role = 'platform_owner'
          and pu.is_active = true;

        if v_active_owner_count <= 1 then
            raise exception
                'Paryx must retain at least one active platform owner.';
        end if;
    end if;

    insert into public.platform_users (
        user_id,
        role,
        is_active,
        updated_at
    )
    values (
        v_target_user_id,
        v_role,
        coalesce(p_is_active, false),
        now()
    )
    on conflict on constraint platform_users_pkey
    do update set
        role = excluded.role,
        is_active = excluded.is_active,
        updated_at = now();

    insert into public.platform_audit_log (
        actor_user_id,
        actor_role,
        action,
        target_user_id,
        details
    )
    values (
        auth.uid(),
        'platform_owner',
        'platform_user_access_updated',
        v_target_user_id,
        jsonb_build_object(
            'email', v_email,
            'previous_role', v_old_role,
            'previous_active', v_old_active,
            'new_role', v_role,
            'new_active', coalesce(p_is_active, false)
        )
    );

    return query
    select
        pu.user_id,
        au.email::text,
        pu.role,
        pu.is_active
    from public.platform_users as pu
    join auth.users as au
        on au.id = pu.user_id
    where pu.user_id = v_target_user_id;
end;
$$;

revoke all
on function public.platform_set_user_access(text, text, boolean)
from public, anon;

grant execute
on function public.platform_set_user_access(text, text, boolean)
to authenticated;


-- =========================================================
-- AUDIT DIRECTORY
-- =========================================================

create or replace function public.platform_get_audit(
    p_limit integer default 100
)
returns table (
    audit_id bigint,
    actor_email text,
    actor_role text,
    action text,
    club_id uuid,
    club_name text,
    target_email text,
    details jsonb,
    created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_limit integer;
begin
    if auth.uid() is null
       or not public.is_platform_user(null) then
        raise exception 'Paryx Console access required.';
    end if;

    v_limit := greatest(
        1,
        least(coalesce(p_limit, 100), 250)
    );

    return query
    select
        pal.id,
        actor.email::text,
        pal.actor_role,
        pal.action,
        pal.club_id,
        c.name,
        target.email::text,
        pal.details,
        pal.created_at
    from public.platform_audit_log as pal
    left join auth.users as actor
        on actor.id = pal.actor_user_id
    left join auth.users as target
        on target.id = pal.target_user_id
    left join public.clubs as c
        on c.id = pal.club_id
    order by pal.created_at desc
    limit v_limit;
end;
$$;

revoke all
on function public.platform_get_audit(integer)
from public, anon;

grant execute
on function public.platform_get_audit(integer)
to authenticated;


-- =========================================================
-- CONSOLE LOGIN AUDIT
-- =========================================================

create or replace function public.platform_record_console_login()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_role text;
begin
    if auth.uid() is null
       or not public.is_platform_user(null) then
        raise exception 'Paryx Console access required.';
    end if;

    select pu.role
    into v_role
    from public.platform_users as pu
    where pu.user_id = auth.uid()
      and pu.is_active = true
    limit 1;

    insert into public.platform_audit_log (
        actor_user_id,
        actor_role,
        action,
        details
    )
    values (
        auth.uid(),
        v_role,
        'console_login',
        '{}'::jsonb
    );
end;
$$;

revoke all
on function public.platform_record_console_login()
from public, anon;

grant execute
on function public.platform_record_console_login()
to authenticated;

commit;
